MvcWebApp/Controllers/TableStorageController.cs
using AzureStorageLibrary;
using AzureStorageLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using MvcWebApp.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebApp.Controllers
{
    public class TableStorageController : Controller
    {
        private readonly INoSqlStorage<Product> _noSqlStorage;

        public TableStorageController(INoSqlStorage<Product> noSqlStorage)
        {
            this._noSqlStorage = noSqlStorage;
        }

        public IActionResult Index()
        {
            ViewBag.Process = ProcessEnum.Get;
            ViewBag.products = _noSqlStorage.All().ToList();
            return View();
        }

        public async Task<IActionResult> Create(Product product)
        {
            product.RowKey = Guid.NewGuid().ToString();
            product.PartitionKey = "Pens";
            await _noSqlStorage.Add(product);
            return RedirectToAction("Index");
        }

        public IActionResult Update(string rowKey, string partitionKey)
        {
            var product = _noSqlStorage.Query(x => x.RowKey == rowKey);
            ViewBag.Process = ProcessEnum.Update;
            ViewBag.products = _noSqlStorage.All().ToList();
            return View("Index", product.FirstOrDefault());
        }

        [HttpPost]
        public async Task<IActionResult> Update(Product product)
        {
            product.ETag = "*";
            ViewBag.Process = ProcessEnum.Update;
            ViewBag.products = _noSqlStorage.All().ToList();
            await _noSqlStorage.Update(product);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string rowKey, string partitionKey)
        {
            await _noSqlStorage.Delete(rowKey, partitionKey);
            return RedirectToAction("Index");
        }
        public IActionResult Query(double price)
        {
            ViewBag.products = _noSqlStorage.Query(x => x.Price > price).ToList();
            ViewBag.Process = ProcessEnum.Get;
            return View("Index");
        }

    }
}

MvcWebApp/Views/TableStorage/Index.cshtml
@using MvcWebApp.Models
@model AzureStorageLibrary.Models.Product

<h2 class="mt-5 mb-4">@(ViewBag.Process==ProcessEnum.Update?"Update Product":"Add Product")</h2>
<form class="form-inline" asp-action="@(ViewBag.Process==ProcessEnum.Update?"Update":"Create")" method="post" enctype="application/x-www-form-urlencoded">
    <input class="form-control mr-1" asp-for="Name" placeholder="Product Name" />
    @if (ViewBag.Process==ProcessEnum.Get)
    {
        <input class="form-control  mr-1"  placeholder="Product Price" />
    }
    else
    {
        <input class="form-control  mr-1" asp-for="Price" placeholder="Product Price">
    }
    <input class="form-control mr-1" asp-for="Stock" placeholder="Product Stock" />
    <input class="form-control mr-1" asp-for="Color" placeholder="Product Color" />
    <input type="hidden" asp-for="RowKey" />
    <input type="hidden" asp-for="PartitionKey" />
    <input type="hidden" asp-for="ETag" />
    <input class="btn btn-primary" type="submit" value="@(ViewBag.Process==ProcessEnum.Update?"Update Product":"Add Product")" />
</form>



<h2 class="mt-5 mb-4">Products</h2>
<form class="form-inline mb-3" asp-action="Query"  method="get">
   
    <input class="form-control mr-2" type="number" name="price" placeholder="Price Filter" />
    <input type="submit" class="btn btn-success" name="query" />
</form>
<table class="table table-bordered">
    <tr>
        <th>RowKey</th>
        <th>PartitionKey</th>
        <th>Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Color</th>
        <th>TimeStamp</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in ViewBag.products as List<AzureStorageLibrary.Models.Product>)
    {
        <tr>
            <td>@item.RowKey</td>
            <td>@item.PartitionKey</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td>@item.Color</td>
            <td>@item.Timestamp</td>
            <td>
                <a class="btn btn-primary btn-sm" asp-action="Update" asp-controller="TableStorage" asp-route-partitionKey=@item.PartitionKey asp-route-rowKey=@item.RowKey><span class="fas fa-edit"></span></a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="TableStorage" asp-route-partitionKey=@item.PartitionKey asp-route-rowKey=@item.RowKey><span class="fas fa-minus-circle"></span></a>
            </td>
        </tr>
    }
</table>